<?php

$exit_states=array(
    array('value'=>'0','description'=>'The API method call was successful.'),
    array('value'=>'1','description'=>'Exception occurred. Please see the ErrorMessage property of the Response object.'),
    array('value'=>'2','description'=>'Response not specified.'),
    array('value'=>'3','description'=>'Authentication failed.'),
    array('value'=>'4','description'=>'No data returned.'),
    array('value'=>'5','description'=>'Error occurred.'),
    array('value'=>'6','description'=>'Not implemented.'),
    array('value'=>'7','description'=>'Invalid request.'),
    array('value'=>'8','description'=>'Card not found.'),
    array('value'=>'9','description'=>'Card not in sellable state.'),
    array('value'=>'10','description'=>'Cards in account not same product.'),
    array('value'=>'11','description'=>'Too many cards for account.'),
    array('value'=>'12','description'=>'Wrong number of cards for account type.'),
    array('value'=>'13','description'=>'Too many cards for cardholder.'),
    array('value'=>'14','description'=>'Error validating identity.'),
    array('value'=>'15','description'=>'Failed identity validation.'),
    array('value'=>'16','description'=>'Would exceed max daily load count.'),
    array('value'=>'17','description'=>'Would exceed max daily load amount.'),
    array('value'=>'18','description'=>'Would exceed max monthly load amount.'),
    array('value'=>'19','description'=>'Would exceed max monthly load count.'),
    array('value'=>'20','description'=>'Would exceed max card balance.'),
    array('value'=>'21','description'=>'Below min load amount.'),
    array('value'=>'22','description'=>'Over max load amount.'),
    array('value'=>'23','description'=>'Card perso already pending.'),
    array('value'=>'24','description'=>'Card reissue already pending.'),
    array('value'=>'25','description'=>'Card already reissued.'),
    array('value'=>'26','description'=>'Account has not opened'),
    array('value'=>'27','description'=>'Card is not valid for customer'),
    array('value'=>'28','description'=>'Card Status not valid for the Request'),
    array('value'=>'29','description'=>'Cards are from different accounts'),
    array('value'=>'30','description'=>'Month not within the Allowed Range'),
    array('value'=>'31','description'=>'Duplicate card numbers.'),
    array('value'=>'32','description'=>'Duplicate cardholders.'),
    array('value'=>'33','description'=>'Card already Closed.'),
    array('value'=>'34','description'=>'Card has pending transactions.'),
    array('value'=>'35','description'=>'Card has positive balance.'),
    array('value'=>'36','description'=>'SSN Match Not Found.'),
    array('value'=>'37','description'=>'Load not found.'),
    array('value'=>'38','description'=>'Load already reversed.'),
    array('value'=>'39','description'=>'Load amount mismatch.'),
    array('value'=>'40','description'=>'Third line embossing validation failure.'),
    array('value'=>'41','description'=>'Card is not reloadable.'),
    array('value'=>'42','description'=>'Integration id not unique.'),
    array('value'=>'43','description'=>'Load amount less than zero.'),
    array('value'=>'44','description'=>'Customer id validation failed'),
    array('value'=>'45','description'=>'Failure'),
    array('value'=>'46','description'=>'Customer id not found'),
    array('value'=>'47','description'=>'Token id Validation failed'),
    array('value'=>'48','description'=>'Product id not found'),
    array('value'=>'49','description'=>'Quantity Validation failed'),
    array('value'=>'50','description'=>'Integer Validation failed'),
    array('value'=>'51','description'=>'Fourth line embossing validation failure.'),
    array('value'=>'52','description'=>'Card order invalid.'),
    array('value'=>'53','description'=>'Card order item invalid.'),
    array('value'=>'54','description'=>'Invalid client certificate.'),
    array('value'=>'55','description'=>'Client certificate not valid for user.'),
    array('value'=>'56','description'=>'User account found cant login.'),
    array('value'=>'57','description'=>'Request object validation failed.'),
    array('value'=>'58','description'=>'User not found.'),
    array('value'=>'59','description'=>'Password invalid.'),
    array('value'=>'60','description'=>'New password invalid.'),
    array('value'=>'61','description'=>'New password in history.'),
    array('value'=>'62','description'=>'Password expired.'),
    array('value'=>'63','description'=>'Secret question not found.'),
    array('value'=>'64','description'=>'Secret question answer incorrect.'),
    array('value'=>'65','description'=>'Personalization data not found.'),
    array('value'=>'66','description'=>'Email verification link invalid.'),
    array('value'=>'67','description'=>'Email verification key invalid.'),
    array('value'=>'68','description'=>'Email not verified.'),
    array('value'=>'69','description'=>'Cardholder not found.'),
    array('value'=>'70','description'=>'Address Length is invalid'),
    array('value'=>'71','description'=>'Name Length is invalid'),
    array('value'=>'72','description'=>'DOB is invalid'),
    array('value'=>'73','description'=>'Invalid Personal ID'),
    array('value'=>'74','description'=>'Invalid card order batch association.'),
    array('value'=>'75','description'=>'CAAS token not present.'),
    array('value'=>'76','description'=>'CAAS policy id not found.'),
    array('value'=>'77','description'=>'Invalid credentials.'),
    array('value'=>'78','description'=>'Positive Balance.'),
    array('value'=>'79','description'=>'Insufficient Balance.'),
    array('value'=>'80','description'=>'CAAS user account locked.'),
    array('value'=>'81','description'=>'Load date in past'),
    array('value'=>'82','description'=>'Load date in future'),
    array('value'=>'83','description'=>'Invalid AccountId'),
    array('value'=>'84','description'=>'Fee type unmodified'),
    array('value'=>'85','description'=>'Registration confirmation link has expired'),
    array('value'=>'86','description'=>'Registration confirmation link has expired'),
    array('value'=>'87','description'=>'Not A gift card.'),
    array('value'=>'88','description'=>'Card has unresolved disputed transaction(s)'),
    array('value'=>'89','description'=>'Inventory less than order request.'),
    array('value'=>'90','description'=>'Caas user account name already exists.'),
    array('value'=>'91','description'=>'Customer name already exists.'),
    array('value'=>'92','description'=>'Caas user expired.'),
    array('value'=>'93','description'=>'Caas user disabled.'),
    array('value'=>'94','description'=>'Error system maintenance scheduled outage.'),
    array('value'=>'95','description'=>'CardArt Profile Name Already Exists'),
    array('value'=>'96','description'=>'Caas user terminated.'),
    array('value'=>'97','description'=>'Caas user locked out/disabled due to security violations.'),
    array('value'=>'98','description'=>'Recurring order template already exists'),
    array('value'=>'99','description'=>'Pin reset not successful or timed out.'),
    array('value'=>'100','description'=>'Pin set not successful or timed out.'),
    array('value'=>'101','description'=>'Card on activation hold.'),
    array('value'=>'102','description'=>'Pin change not successful or timed out.'),
    array('value'=>'103','description'=>'Success with user message.'),
    array('value'=>'104','description'=>'Card not reissuable.'),
    array('value'=>'105','description'=>'ACH not allowed for card.'),
    array('value'=>'106','description'=>'ACH routing and account number not unique.'),
    array('value'=>'107','description'=>'ACH name not unique.'),
    array('value'=>'108','description'=>'Invalid ACH info update.'),
    array('value'=>'109','description'=>'ACH account info already validated.'),
    array('value'=>'110','description'=>'ACH info not in valid status to validate.'),
    array('value'=>'111','description'=>'ACH info validation amounts do not match.'),
    array('value'=>'112','description'=>'Cardholder failed ach info validation.'),
    array('value'=>'113','description'=>'Real time ad-hoc report request timed out.'),
    array('value'=>'114','description'=>'Identity blocked for sale.'),
    array('value'=>'115','description'=>'Continue identity validation.'),
    array('value'=>'116','description'=>'The cardholder id type not allowed'),
);